
spring:
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml
  cloud:
    config:
      fail-fast: true
  mvc:
    format:
      date: iso
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jawh
    password: password
    url: jdbc:postgresql://postgres:5432/post_db
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
  kafka:
    producer:
      acks: all
      bootstrap-servers: kafka-1:9092,kafka-2:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      properties:
        delivery.timeout.ms: 20000
        request.timeout.ms: 1000
        linger.ms: 0
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery:8761/eureka
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
