logging:
  level:
    root: info

spring:
  mvc:
    format:
      date: iso
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5433/authDB
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create


