
logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

spring:
  cloud:
    config:
      fail-fast: true
  kafka:
    producer:
      acks: all
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      properties:
        delivery.timeout.ms: 20000
        request.timeout.ms: 1000
        linger.ms: 0
  mvc:
    format:
      date: iso
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jawh
    password: password
    url: jdbc:postgresql://localhost:5434/auth_db
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


