
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: profile-service
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      group-id: profile-service-group
    producer:
      acks: all
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      properties:
        delivery.timeout.ms: 20000
        request.timeout.ms: 1000
        linger.ms: 0
  cloud:
    config:
      fail-fast: true
  mvc:
    format:
      date: iso
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jawh
    password: password
    url: jdbc:postgresql://localhost:5434/profile_db
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true

logging:
  level:
    root: info

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30